	// DRAM clks
	__DRAM__ {CCMU_REG_DRAMPLL, 31}, // CCMU_MCLK_DRAM_MACC
	__DRAM__ {CCMU_REG_DRAMPLL, 30},	// CCMU_MCLK_DRAM_DEFE
	__DRAM__ {CCMU_REG_DRAMPLL, 29},	// CCMU_MCLK_DRAM_DEBE
	__DRAM__ {CCMU_REG_DRAMPLL, 28}, // CCMU_MCLK_DRAM_CSI
	__DRAM__ {CCMU_REG_DRAMPLL, 27},	// CCMU_MCLK_DRAM_TS