	// APB clocks
	__APB__ {CCMU_REG_APBMOD, 14},	// CCMU_MCLK_APB_PS2
	__APB__ {CCMU_REG_APBMOD, 13},	// CCMU_MCLK_APB_AC97
	__APB__ {CCMU_REG_APBMOD, 12},	// CCMU_MCLK_APB_SPDIF
	__APB__ {CCMU_REG_APBMOD, 11},	// CCMU_MCLK_APB_IIS
	__APB__ {CCMU_REG_APBMOD, 10},	// CCMU_MCLK_APB_IR
	__APB__ {CCMU_REG_APBMOD,  9},	// CCMU_MCLK_APB_CODEC
	__APB__ {CCMU_REG_APBMOD,  8},	// CCMU_MCLK_APB_UART3
	__APB__ {CCMU_REG_APBMOD,  7},	// CCMU_MCLK_APB_UART2
	__APB__ {CCMU_REG_APBMOD,  6},	// CCMU_MCLK_APB_UART1
	__APB__ {CCMU_REG_APBMOD,  5},	// CCMU_MCLK_APB_UART0
	__APB__ {CCMU_REG_APBMOD,  4},	// CCMU_MCLK_APB_PIO
	__APB__ {CCMU_REG_APBMOD,  3},	// CCMU_MCLK_APB_TWI1
	__APB__ {CCMU_REG_APBMOD,  2},	// CCMU_MCLK_APB_TWI0